Introdução Leitura de Arquivos

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as mat
pd.read_excel('Chess.xlsx')
pd.read_csv('Tomato.csv')

df_excel = pd.read_excel("Chess.xlsx", sheet_name="Chess")
df_csv = pd.read_csv("Tomato.csv", sep =",")

df_excel.head(2) # primeiras linhas


,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,opening_eco,opening_name,opening_ply
0,False,1.504210e+17,1.504210e+17,13,outoftime,white,15+2,bourgris,1500,a-00,1191,D10,Slav Defense: Exchange Variation,5
1,True,1.504130e+17,1.504130e+17,16,resign,black,5+10,a-00,1322,skinnerua,1261,B00,Nimzowitsch Defense: Kennedy Variation,4


In [20]:
df_csv.tail() # ultimas linhas

,Date,Unit,Minimum,Maximum,Average,Market
2736,2021-05-09,Kg,10,15,12.5,Tomato
2737,2021-05-10,Kg,10,15,12.5,Tomato
2738,2021-05-11,Kg,10,15,12.5,Tomato
2739,2021-05-12,Kg,30,35,32.5,Tomato
2740,2021-05-13,Kg,35,40,37.5,Tomato


In [22]:
df_csv.shape


(2741, 6)

In [ ]:
df_excel.info() #trazer a descrição da coluna

<class 'pandas.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  str    
 5   winner          20058 non-null  str    
 6   increment_code  20058 non-null  str    
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  str    
 12  opening_name    20058 non-null  str    
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(2), str(5)
memory usage: 2.0+ MB


In [ ]:
df_csv.describe().T #transpor o describe


,count,mean,std,min,25%,50%,75%,max
Minimum,2741.0,35.089748,16.648425,8.0,22.0,30.0,45.0,115.0
Maximum,2741.0,41.281284,17.364135,12.0,30.0,38.0,50.0,120.0
Average,2741.0,38.185516,16.970949,10.0,25.0,35.0,47.5,117.5


In [ ]:
df_excel.head() #trazer os dados

,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,opening_eco,opening_name,opening_ply
0,False,1.504210e+17,1.504210e+17,13,outoftime,white,15+2,bourgris,1500,a-00,1191,D10,Slav Defense: Exchange Variation,5
1,True,1.504130e+17,1.504130e+17,16,resign,black,5+10,a-00,1322,skinnerua,1261,B00,Nimzowitsch Defense: Kennedy Variation,4
2,True,1.504130e+17,1.504130e+17,61,mate,white,5+10,ischia,1496,a-00,1500,C20,King's Pawn Game: Leonardis Variation,3
3,True,1.504110e+17,1.504110e+17,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,D02,Queen's Pawn Game: Zukertort Variation,3
4,True,1.504030e+17,1.504030e+17,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,C41,Philidor Defense,5


In [ ]:
set(df_excel["victory_status"]) #verficar o que temos nas colunas

{'draw', 'mate', 'outoftime', 'resign'}

In [28]:
df_csv.head()

,Date,Unit,Minimum,Maximum,Average,Market
0,2013-06-16,Kg,26,32,29.0,Tomato
1,2013-06-17,Kg,20,25,22.5,Tomato
2,2013-06-18,Kg,22,26,24.0,Tomato
3,2013-06-19,Kg,24,28,26.0,Tomato
4,2013-06-20,Kg,22,26,24.0,Tomato


In [32]:
df_csv.describe()

,Minimum,Maximum,Average
count,2741.000000,2741.000000,2741.000000
mean,35.089748,41.281284,38.185516
std,16.648425,17.364135,16.970949
min,8.000000,12.000000,10.000000
25%,22.000000,30.000000,25.000000
50%,30.000000,38.000000,35.000000
75%,45.000000,50.000000,47.500000
max,115.000000,120.000000,117.500000


In [33]:
def categorizar_tomate_media (media):
    if  media >=40 and media <= 70:
        return "tomate médio"
    elif media < 40:
        return "tomate pequeno"
    else:
        return "Tomatão"
    

In [ ]:
#criando uma coluna nova com base na função anterior 
df_csv["categoria_tomate"] = df_csv["Average"].apply(categorizar_tomate_media)

In [ ]:
# verificando a coluna criada, ela já aprece nos dados
df_csv.head()

,Date,Unit,Minimum,Maximum,Average,Market,categoria_tomate
0,2013-06-16,Kg,26,32,29.0,Tomato,tomate pequeno
1,2013-06-17,Kg,20,25,22.5,Tomato,tomate pequeno
2,2013-06-18,Kg,22,26,24.0,Tomato,tomate pequeno
3,2013-06-19,Kg,24,28,26.0,Tomato,tomate pequeno
4,2013-06-20,Kg,22,26,24.0,Tomato,tomate pequeno


In [ ]:
df_csv.groupby(["categoria_tomate"]).describe() #criando a estatistica da função criada de tomate

Minimum                                                      \
                   count       mean       std   min   25%   50%   75%    max   
categoria_tomate                                                               
Tomatão            149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   
tomate médio       954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
tomate pequeno    1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
categoria_tomate                     ...                                   
Tomatão            149.0  82.583893  ...  85.0  120.0   149.0  79.164430   
tomate médio       954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
tomate pequeno    1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   

                                                           
                       std   min   25%   50%   75%    max  
categoria_tomate                                           
Tomatão           7.367396  70.5  75.0  77.5  82.5  117.5  
tomate médio      8.272792  40.0  45.0  50.0  57.5   70.0  
tomate pequeno    7.191735  10.0  21.5  27.5  32.5   39.5  

[3 rows x 24 columns]

In [43]:
# Criando filtros
filtro = df_csv["Average"] < 40
df_csv.loc[filtro]

,Date,Unit,Minimum,Maximum,Average,Market,categoria_tomate
0,2013-06-16,Kg,26,32,29.0,Tomato,tomate pequeno
1,2013-06-17,Kg,20,25,22.5,Tomato,tomate pequeno
2,2013-06-18,Kg,22,26,24.0,Tomato,tomate pequeno
3,2013-06-19,Kg,24,28,26.0,Tomato,tomate pequeno
4,2013-06-20,Kg,22,26,24.0,Tomato,tomate pequeno
...,...,...,...,...,...,...,...
2736,2021-05-09,Kg,10,15,12.5,Tomato,tomate pequeno
2737,2021-05-10,Kg,10,15,12.5,Tomato,tomate pequeno
2738,2021-05-11,Kg,10,15,12.5,Tomato,tomate pequeno
2739,2021-05-12,Kg,30,35,32.5,Tomato,tomate pequeno


MATRIZ

In [ ]:
#criando uma matriz
import numpy as np
arr_list = np.array([1.2,3,4,5,6,7,8])
print(arr_list)

[1.2 3.  4.  5.  6.  7.  8. ]


In [52]:
#criando matriz de zeros
arr_zeros = np.zeros((4,6))
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [54]:
#criando matriz com numeros
arr_ones = np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
#criando matriz com numeros aleatorios
arr_random = np.random.rand(3,4)
print(arr_random)

[[0.0463933  0.3013624  0.94709401 0.62859083]
 [0.08387666 0.47686734 0.23382196 0.75585945]
 [0.27434864 0.21107543 0.63942831 0.99988214]]


In [ ]:
#verificar dimensão do array com shape
print(arr_random.shape)

(3, 4)


In [ ]:
#trocando o formato do array
arr_random_reshape = arr_random.reshape((4,3))
print(arr_random_reshape)

[[0.0463933  0.3013624  0.94709401]
 [0.62859083 0.08387666 0.47686734]
 [0.23382196 0.75585945 0.27434864]
 [0.21107543 0.63942831 0.99988214]]


In [70]:
# criando varios arrays para juntar
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

arr4 = np.concatenate ((arr1, arr2, arr3), axis=1)
arr4

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [ ]:
#dividindo array
arr4_split = np.split(arr4,2)
print(arr4_split)

[array([[ 1,  2,  5,  6,  9, 10]]), array([[ 3,  4,  7,  8, 11, 12]])]


In [74]:
#transpor array
arr4_transpose = np.transpose(arr4)
print(arr4_transpose)

[[ 1  3]
 [ 2  4]
 [ 5  7]
 [ 6  8]
 [ 9 11]
 [10 12]]


In [75]:
#retirar do transpor
arr4_revertido =arr4_transpose.T
print(arr4_revertido)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [77]:
#soma de array
arr_a = np.array([1, 7, 27])
arr_b = np.array([1, 5, 1])
arr_a_b = np.add(arr_a, arr_b)
print(arr_a_b)

[ 2 12 28]


In [78]:
#subtração de array
arr_sub_a_b = np.subtract(arr_a, arr_b)
print(arr_sub_a_b)

[ 0  2 26]
